### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by CameronEx** [CameronEx/osx-myair#1]
https://github.com/CameronEx/osx-myair/blob/50dc72d5dc708113d50d7503837aaa0f0ae74943/osx-myair/__main__.py#L59

```
Traceback (most recent call last):
  File "osx-myair/__main__.py", line 6, in <module>
    class MyAirTaskbar(rumps.App):
  File "osx-myair/__main__.py", line 40, in MyAirTaskbar
    @rumps.timer(self.poll_int)
NameError: name 'self' is not defined
```

**Comment by CameronEx** [comment]
Can't access `self` at definition time. Can patch by modifying decorator and checking the input variable at run time... but later.

![alt text][themoreyouknow]

[themoreyouknow]: https://change-production.s3.amazonaws.com/photos/wordpress_copies/nbc_the_more_you_know1-300x197.jpg
